### ISSUE TITLE
User screen column resizing is broken

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom-auth#132] opened 2019-02-12 08:34 UTC
Column resizing is broken in the User screen, @jc064522 is aware

If you drag a column to make it wider, it jumps to a larger fixed size, then is not resizeable

**Comment by jc064522** [comment] 2019-11-05 12:55
I saw things happening on live but cannot reproduce it. I've updated dependencies since then so maybe that's fixed it. I'll close this but @stroomdev10 please feel free to reopen it if it's still there after the next release.

**Closed by jc064522** 2019-11-05 12:55 UTC
Labels: bug
