### ISSUE TITLE
Consistent date formatting please

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom-auth#131] opened 2019-02-12 08:21 UTC
Please change all the auth screens to use ISO standard date format, this will bring them into line with the rest of the application.

I'd like then date in UTC, but other installations may desire an alternative time offset

**Comment by jc064522** [comment] 2019-11-05 10:18
Duplicate of https://github.com/gchq/stroom-auth/issues/125

**Closed by jc064522** 2019-11-05 10:18 UTC
Labels: bug
